#!/usr/bin/env python3
"""Pull the webfonts and GSAP local, so a visit makes no third-party request.

Every page was loading fonts from fonts.googleapis.com/fonts.gstatic.com and
GSAP from cdn.jsdelivr.net. None of that sets a cookie, but each one hands the
visitor's IP address and user agent to a company they did not choose to
contact, which is the part GDPR actually cares about. Self-hosting removes the
question rather than disclosing it.

Run this when a level adds a typeface. It writes:
  src/fonts/*.woff2       the font files
  src/css/fonts.css       @font-face rules pointing at them
  src/js/vendor/*.js      gsap + ScrollTrigger

Usage: python3 tools/fetch_vendor.py
"""

import json
import pathlib
import re
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "src" / "fonts"
VENDOR = ROOT / "src" / "js" / "vendor"
CSS_OUT = ROOT / "src" / "css" / "fonts.css"

# A modern UA, or Google serves ttf instead of woff2.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

# Latin only. The site is English and every level name renders in it; the
# Japanese on Kyouki comes from the system stack, not a webfont.
KEEP_SUBSETS = ("latin", "latin-ext")

BASE_FAMILIES = [
    "Archivo:wght@400;600;900",
    "IBM+Plex+Mono:wght@400;500",
]

GSAP = [
    ("gsap.min.js", "https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js"),
    ("ScrollTrigger.min.js",
     "https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/ScrollTrigger.min.js"),
]


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def families() -> list[str]:
    fams = set(BASE_FAMILIES)
    for jf in sorted((ROOT / "data" / "levels").glob("*.json")):
        rec = json.loads(jf.read_text(encoding="utf-8"))
        for f in rec["theme"].get("googleFonts") or []:
            fams.add(f)
    return sorted(fams)


BLOCK = re.compile(r"/\*\s*([a-z-]+)\s*\*/\s*(@font-face\s*\{.*?\})", re.S)
URL = re.compile(r"url\((https://fonts\.gstatic\.com/[^)]+)\)")


def main():
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    VENDOR.mkdir(parents=True, exist_ok=True)

    rules: list[str] = []
    seen: set[str] = set()
    files = 0

    for spec in families():
        css = get(f"https://fonts.googleapis.com/css2?family={spec}"
                  "&display=swap").decode("utf-8")
        for subset, block in BLOCK.findall(css):
            if subset not in KEEP_SUBSETS:
                continue
            m = URL.search(block)
            if not m:
                continue
            remote = m.group(1)
            name = remote.rsplit("/", 1)[-1]
            if name not in seen:
                (FONT_DIR / name).write_bytes(get(remote))
                seen.add(name)
                files += 1
            rules.append(block.replace(remote, f"/assets/fonts/{name}"))
        print(f"  {spec}")

    header = (
        "/* fonts.css — generated by tools/fetch_vendor.py. Do not edit.\n"
        "   Self-hosted so that loading a page makes no request to any host\n"
        "   but this one. Latin and latin-ext only. */\n\n"
    )
    CSS_OUT.write_text(header + "\n".join(rules) + "\n", encoding="utf-8")

    for name, url in GSAP:
        (VENDOR / name).write_bytes(get(url))
        print(f"  {name}")

    kb = sum(f.stat().st_size for f in FONT_DIR.glob("*.woff2")) / 1024
    print(f"\n{files} font files ({kb:.0f} KB), {len(rules)} @font-face rules")


if __name__ == "__main__":
    main()
